halvardssm/deno-nessie

.github/workflows/ci.yml, Makefile, README.md, cli.ts, cli/mysql.ts, cli/pgsql.ts, cli/sqlite.ts, cli/state.ts, cli/utils.ts, import_map.json, nessie.config.ts, src/Column.ts, src/Schema.ts, src/Table.ts, tests/column.test.ts, tests/config/migration.config.ts, tests/migration.test.ts, tests/schema.mysql.test.ts, tests/schema.pg.test.ts, tests/table.mysql.test.ts, tests/table.pg.test.ts
=> Upgrade deno 0.42

Makefile, cli.ts, cli/state.ts, cli/utils.ts, deps.ts, mod.ts, nessie.config.ts, src/Column.ts, src/Schema.ts, src/Table.ts, src/TypeUtils.ts, tests/config/mysql.config.ts, tests/config/pg.config.ts, tests/config/sqlite.config.ts, tests/migration.test.ts, tests/schema.mysql.test.ts, tests/schema.pg.test.ts
=> added support for Deno v1.0

cli/utils.ts
Fixes #23 . The order of migrations was reversed.
=> Swap position of sort parameters

query-builder/Schema.ts, tests/query-builder/schema.mysql.test.ts, tests/query-builder/schema.pg.test.ts, tests/query-builder/schema.sqlite.test.ts
Update queryString function to return the string  and add it to the schema query as well #37
=> Fix queryString function to return the string 

README.md, cli/templates/config.ts, cli/templates/migration.ts, clients/AbstractClient.ts, examples/migration-basic.ts, examples/migration-column-config.ts, examples/migration-third-party.ts, mod.ts, query-builder/Schema.ts, query-builder/Table.ts, tests/cli/1587937822648-test1.ts, tests/cli/1587937822649-test2.ts, tests/cli/1587937822650-test3.ts, tests/query-builder-migrations/1587937822648-basics.ts, tests/query-builder-migrations/1587937822649-numerics.ts, tests/query-builder-migrations/1587937822650-strings-misc.ts, tests/query-builder/schema.mysql.test.ts, tests/query-builder/schema.pg.test.ts, tests/query-builder/schema.sqlite.test.ts, types.ts
=> Changed schema to use array instead of string for queries

README.md, cli.ts, cli/state.ts, cli/templates/config.ts, cli/templates/migration.ts, cli/templates/seed.ts, cli/utils.ts, clients/AbstractClient.ts, clients/ClientMySQL.ts, clients/ClientPostgreSQL.ts, clients/ClientSQLite.ts, examples/migration-using-connection.ts, query-builder/Column.ts, query-builder/Schema.ts, query-builder/Table.ts, query-builder/TypeUtils.ts, tests/query-builder/schema.mysql.test.ts, tests/query-builder/schema.pg.test.ts, tests/query-builder/schema.sqlite.test.ts, tests/query-builder/table.mysql.test.ts, tests/query-builder/table.pg.test.ts, tests/query-builder/table.sqlite.test.ts, types.ts
Related to #1 
Please review the [guidelines for contributing](https://github.com/halvardssm/deno-nessie/blob/master/.github/CONTRIBUTING.md) to this repository.
Minor changes for release candidate 1
=> Release candidate 1

examples/migration-third-party.ts, examples/migration-using-connection.ts, types.ts
Relates to #1 
Please review the [guidelines for contributing](https://github.com/halvardssm/deno-nessie/blob/master/.github/CONTRIBUTING.md) to this repository.
Release candidate 2
=> Release candidate 2

README.md, cli.ts, clients/AbstractClient.ts
Closes #59 
Please review the [guidelines for contributing](https://github.com/halvardssm/deno-nessie/blob/master/.github/CONTRIBUTING.md) to this repository.
Final update before v1.0 release! 🎉
=> Release candidate 3

cli/state.ts
Fixes #
Please review the [guidelines for contributing](https://github.com/halvardssm/deno-nessie/blob/master/.github/CONTRIBUTING.md) to this repository.
Fixes the bug in `make:seed` to create the seed file in the right directory.
=> Fixing bug in make:seed to create template seed in seedFolder

CHANGELOG.md, clients/AbstractClient.ts
=> fix resolve bug

CHANGELOG.md, README.md, cli.ts, clients/AbstractClient.ts, clients/ClientMySQL.ts, clients/ClientPostgreSQL.ts, clients/ClientSQLite.ts, deps.ts, tests/integration/cli/cli.test.ts, tests/integration/cli/config/cli.config.ts, tests/integration/update_timestamps/update_timestamps.test.ts, types.ts
Fixes #129 
Some short description of what this PR solves if it is not covered by the
related issue
=> Added status command

README.md, cli.ts, consts.ts, deps.ts
=> Added donation notices

clients/ClientPostgreSQL.ts, clients/ClientSQLite.ts, examples/config-postgres-connection-string.ts
Support all constructor parameter patterns of `deno-postgres` client.
=> enable ConnectionString usage in pg client

deps.ts
Fixes #
Just bump `deno-postgres` to v0.13.0
=> Upgrade `deno-postgres` to v0.13.0

README.md
Fixes #137 
- N/A Updated JSDoc (for methods changed/added)
- [N/A Added tests to cover added functionalities.
- N/A Added/updated examples in example folder.
- [] Make sure the pipeline passes.
Adds a note about restricting perissions.
Felt the readme was clightly hard to digest, so i thought of splitting it into sections, let me know what you think: https://github.com/ebebbington/deno-nessie/blob/restrict-perms/README.md#contents
=> chore: Add note about restricting permissions and organise README

.github/workflows/ci.yml, CHANGELOG.md, README.md, cli.ts, cli/state.ts, examples/README.md, examples/abstract-classes-extended.ts, examples/config-custom-templates.ts, examples/migration-template.ts, examples/seed-template.ts, types.ts
Fixes #132 
Some short description of what this PR solves if it is not covered by the
related issue
=> Added support for custom migration and seed templates

deps.ts
Fixes #
fixes issues that dead-lock the library on Windows when running with `--unstable`
https://github.com/dyedgreen/deno-sqlite/commit/f34c14a3d506eeba4e87bf039f7838421368b2ab
=> update sqlite plugin version

deps.ts
Fixes #
This PR attempts to update the SQLite dependency to the latest version (3.4.0), since it introduces a method within the client that's actually useful: `execute`. No breaking changes should be expected, since there are no deprecations or API changes on the existing methods on the library.
=> Bump SQLIte version to 3.4.0

README.md, clients/ClientPostgreSQL.ts
Fixes #
Some short description of what this PR solves if it is not covered by the
related issue
=> Allow pg adaptor to work with CockroachDB

deps.ts
This sorts out a deprecation [fixed on that version](https://github.com/denodrivers/mysql/releases/tag/v2.10.3)
Fixes #160
Some short description of what this PR solves if it is not covered by the
related issue
=> fix(deps): update `mysql` to v2.10.3
